"use strict";

/**
 * providerCredentials.js — Write decrypted provider API keys to the OpenClaw
 * credential file so the gateway's LiteLLM router can find them.
 *
 * SECURITY CONTRACT:
 *   - Decryption happens here, in the main process only.
 *   - Keys are written to ~/.openclaw/.env.hivemind (a local file, not sent anywhere).
 *   - The file is created with restrictive permissions (0o600) where supported.
 *   - This file is auto-generated — the gateway should source it or load it.
 *   - Keys are NEVER logged, NEVER returned to the renderer, NEVER put in openclaw.json.
 */

const fs = require("fs").promises;
const path = require("path");
const { getOpenClawBase } = require("./pathUtils");

// LiteLLM environment variable names per provider type.
// `authKey` is a fixed value written unconditionally (no decryption needed).
const PROVIDER_ENV_VARS = {
  gemini: { key: "GEMINI_API_KEY" },
  openai: { key: "OPENAI_API_KEY", baseUrl: "OPENAI_API_BASE" },
  anthropic: { key: "ANTHROPIC_API_KEY" },
  // Ollama: OpenClaw requires OLLAMA_API_KEY to be set (any non-empty value).
  // See: https://docs.openclaw.ai/providers/ollama
  ollama: { authKey: ["OLLAMA_API_KEY", "ollama-local"], baseUrl: "OLLAMA_API_BASE" },
  "openai-compatible": { key: "OPENAI_API_KEY", baseUrl: "OPENAI_API_BASE" },
};

/**
 * Write provider credentials to ~/.openclaw/.env.hivemind.
 * Called after agent config is regenerated so the gateway always has fresh credentials.
 *
 * @returns {Promise<{ written: boolean, path: string }>}
 */
async function writeProviderCredentials() {
  try {
    // Lazy-require to avoid circular deps at module load time
    const {
      getProviderStore,
      decryptProviderKey,
    } = require("../ipc/providerHandlers");

    const ps = await getProviderStore();
    const rawProviders = ps.get("providers") || {};
    const enabledProviders = Object.values(rawProviders).filter((p) => p.enabled);

    const lines = [
      "# Auto-generated by HiveMind OS — do not edit manually.",
      "# This file is re-written on every agent config update.",
      "# Source this file in your OpenClaw gateway startup script.",
      "",
    ];

    // Track which env vars we've already written (first configured provider wins)
    const written = new Set();

    for (const provider of enabledProviders) {
      const envVars = PROVIDER_ENV_VARS[provider.type];
      if (!envVars) continue;

      // Write fixed auth key (e.g. OLLAMA_API_KEY=ollama-local — any value works)
      if (envVars.authKey && !written.has(envVars.authKey[0])) {
        lines.push(`${envVars.authKey[0]}=${envVars.authKey[1]}`);
        written.add(envVars.authKey[0]);
      }

      // Write encrypted API key
      if (envVars.key && !written.has(envVars.key)) {
        const key = await decryptProviderKey(provider.id);
        if (key) {
          lines.push(`${envVars.key}=${key}`);
          written.add(envVars.key);
        }
      }

      // Write base URL
      if (envVars.baseUrl && provider.baseUrl && !written.has(`${envVars.baseUrl}_${provider.type}`)) {
        lines.push(`${envVars.baseUrl}=${provider.baseUrl}`);
        written.add(`${envVars.baseUrl}_${provider.type}`);
      }
    }

    lines.push(""); // trailing newline

    const outputPath = path.join(getOpenClawBase(), ".env.hivemind");
    await fs.mkdir(getOpenClawBase(), { recursive: true });
    await fs.writeFile(outputPath, lines.join("\n"), { encoding: "utf-8", mode: 0o600 });

    return { written: true, path: outputPath };
  } catch (err) {
    // Non-fatal — log but don't crash the app
    console.error("[providerCredentials] Failed to write credentials:", err.message);
    return { written: false, path: null };
  }
}

module.exports = { writeProviderCredentials };
